version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prompt-health-checker"
s3_prefix = "prompt-health-checker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
resolve_s3 = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
